# APP DEPLOYMENT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: localhost:5000/nginx-service:0.1.2
        ports:
        - containerPort: 80


---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 100
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  type: LoadBalancer